[project]
name = "backend"
version = "0.1.0"
description = "ROCKALPHA FastAPI Backend"
authors = [
    {name = "Devin"}
]
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.135.0,<1.0.0)",
    "uvicorn (>=0.42.0,<1.0.0)",
    "sqlalchemy (>=2.0.0,<3.0.0)",
    "pydantic (>=2.0.0,<3.0.0)",
    "pydantic-settings (>=2.0.0,<3.0.0)",
    "requests (>=2.30.0,<3.0.0)",
    "fastapi[standard] (>=0.135.3,<0.136.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
